name: Develop Tag Actions

on:
  create:
    branches-ignore:
     - master
    tags:
      - r*
jobs:
  create-release-pr:
    uses: apple-industries/github-workflows/.github/workflows/create-release-pr.yml@v1.0.6
