name: Release and Tag
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project
        
    - name: Tag snapshot
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.project.outputs.version }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.project.outputs.version }}
        name: ${{ steps.date.outputs.date }}
        body: ${{ steps.tag_version.outputs.changelog }}
